{{ if not .Values.developmentMode }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: "{{ .Values.name }}-autoscaler"
  namespace: "{{ .Values.namespace }}"

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.name }}"

  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.maxReplicaCount }}
  targetCPUUtilizationPercentage: {{ .Values.scalingCPUTarget }}
{{ end }}
