apiVersion: v1
kind: ConfigMap

metadata:
  name: "{{ .Values.name }}-config"
  namespace: "{{ .Values.namespace }}"

data:
  config.yaml: |
    log:
      level: "{{ .Values.app.log.level }}"

    temporal:
      host: "{{ .Values.app.temporal.host }}"
      port: {{ .Values.app.temporal.port }}
      queue: "{{ .Values.app.temporal.queue }}"
      namespace: "{{ .Values.app.temporal.namespace }}"
      max_concurrent: {{ .Values.app.temporal.max_concurrent }}
