{{ if .Values.developmentMode }}
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: "{{ .Values.namespace }}"
  name: "temporalserver"

  labels:
    app: temporalserver
    owner: "{{ .Values.owner }}"

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: temporalserver

  strategy:
    type: Recreate

  template:

    metadata:

      labels:
        app: temporalserver
        owner: "{{ .Values.owner }}"

      annotations:
        {{ if not .Values.developmentMode }}
        # do not enable on Docker for Mac, since it doesn't support AppArmor
        container.apparmor.security.beta.kubernetes.io/{{ .Values.name }}: runtime/default
        {{ end }}

    spec:

      restartPolicy: Always

      automountServiceAccountToken: false

      containers:
      -
        image: temporalio/server:1.22.1.0
        name: temporalserver

        {{ if .Values.developmentMode }}
        command: ["temporal", "server", "start-dev", "--ip=0.0.0.0", "--port=7233"]
        {{ end }}

        startupProbe:
          grpc:
            port: 7233
          failureThreshold: 10
          periodSeconds: 1

        ports:
        -
          name: temporalrpc
          containerPort: 7233
        -
          name: temporalweb
          containerPort: 8233

        env:
        -
          name: ENABLE_ES
          value: "false"
        -
          name: LOG_LEVEL
          value: INFO

{{ end }}
