{{ if .Values.developmentMode }}
apiVersion: v1
kind: Service

metadata:
  namespace: "{{ .Values.namespace }}"
  name: "temporalserver"

spec:
  selector:
    app: temporalserver

  ports:
  -
    protocol: TCP
    port: 7233
    targetPort: 7233

{{ end }}