
namespace: dev-temporal

developmentMode: true
devWorkingDirectory: ""

image:
  tag: "0.0"

app:
  log:
    level: trace

  temporal:
    host: temporal
    port: 3333
    namespace: temporal
    queue: ""
