# namespace to deploy to
namespace: "temporal"

# name of the chart
name: "temporal"

# owner of the chart
owner: "ironsecurity"

# enable some stuff for local development
developmentMode: false

# service port
servicePort: 9300

# default replica count
replicaCount: 1
maxReplicaCount: 10
scalingCPUTarget: 70

# k8s sa
serviceAccount: "temporal"


# container image specific settings
image:
  # repository to pull image from
  repository: "temporaltest"
  tag: "0.0.0"

app:

  log:
    level: info

  temporal:
    max_concurrent: 0
    queue: main
    namespace: default
